---
kind: pipeline
name: default
node:
  region: cn
steps:
  - name: docker-cn
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: ccr.ccs.tencentyun.com/xiaoqidun/pfenv
      registry: ccr.ccs.tencentyun.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
  - name: docker-hk
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: hkccr.ccs.tencentyun.com/xiaoqidun/pfenv
      registry: hkccr.ccs.tencentyun.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
