---
kind: pipeline
type: docker
name: docker

steps:
  - name: docker
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: xiaoqidun/pfenv
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
